version = 1
test_patterns = [
  "Laravel/tests/**"
]
exclude_patterns = [
  "Laravel/vendor/**"
]

[[analyzers]]
name = "php"
enabled = true

  [analyzers.php]
  runtime_version = "8.1"
  install_composer_dependencies = true
  analyze_tests = true
  source_directory = "Laravel"


  [analyzers.meta]
  bootstrap_files = ["Laravel/config/bootstrap.php"]

#[[analyzers]]

#name = "test-coverage"
#enabled = true

#  [analyzers.test-coverage]
#  report_glob = "Laravel/coverage.xml/index.xml"


