services:
  laravel_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel_app_dev
      #    networks:
      #- laravel_network

      # nginx:
      # image: nginx:latest
      #container_name: nginx
      #ports:
      #- "8080:80"
      #volumes:
      #- ./nginx.conf:/etc/nginx/conf.d/default.conf
      #depends_on:
      #- laravel_app
      #networks:
      #- laravel_network

      #networks:
      #laravel_network:
      #driver: bridge

